
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProyectoPrograV
{

using System;
    using System.Collections.Generic;
    
public partial class Periodo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Periodo()
    {

        this.Grupos = new HashSet<Grupos>();

    }


    public int Anno { get; set; }

    public byte NumeroPeriodo { get; set; }

    public System.DateTime Fecha_Inicio { get; set; }

    public System.DateTime Fecha_Fin { get; set; }

    public string Estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Grupos> Grupos { get; set; }

}

}
